@host = http://localhost:3001

###
GET {{host}}/api/projects

###
POST {{host}}/api/projects
Content-Type: application/json

{
    "title": "test2",
    "description": "test desc",
    "creationDate": "20230505",
    "available": "true"
}

###
PUT {{host}}/api/projects/FXns2kfvY5vjKZClxVcS8
Content-Type: application/json

{
    "description": "new description"
}