@host = http://localhost:3001

###
GET {{host}}/api/projects

###
POST {{host}}/api/projects
Content-Type: application/json

{
    "title": "test2",
    "description": "test desc",
    "creationDate": "20230505",
    "available": "true"
}

###
PUT {{host}}/api/projects/FXns2kfvY5vjKZClxVcS8
Content-Type: application/json

{
    "description": "new description"
}

###
PUT {{host}}/api/projects/FXns2kfvY5vjKZClxVcS8/notavailable
Content-Type: application/json

{
    "available": "true"
}


###
DELETE {{host}}/api/projects/1

###
GET {{host}}/api/users

###
POST {{host}}/api/users
Content-Type: application/json
x-creator: 12345

{
    "username":"juan",
    "email":"juan@mail.com",
    "password":"1234"
}

###
PUT {{host}}/api/users
Content-Type: application/json

{
    "email":"juan1@mail.com"
}

###
DELETE {{host}}/api/users